# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 18:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='monthly_order10',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='monthly_order11',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='monthly_order12',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='monthly_order5',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='monthly_order6',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='monthly_order7',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='monthly_order8',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='monthly_order9',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
