# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('member_required', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('cost_index', models.DecimalField(decimal_places=1, max_digits=50)),
                ('delivery_index', models.DecimalField(decimal_places=1, max_digits=50)),
                ('quality_index', models.DecimalField(decimal_places=1, max_digits=50)),
                ('yearly_binding', models.BooleanField(default=False)),
                ('delivery_time', models.IntegerField(default=30, help_text='in days')),
                ('rm_cost', models.IntegerField(default=500, verbose_name='Per Unit Cost')),
                ('vendor_cost', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
