# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20170430_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='slug',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name of the vendor'),
        ),
    ]
