# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_vendor_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='test',
        ),
    ]
