# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 20:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_remove_vendor_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='test',
            field=models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
