# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_vendor_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='test',
            new_name='rupa',
        ),
    ]
