# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 20:46
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('new', '0006_auto_20170602_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor2',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('monthly_order4', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)])),
                ('monthly_order5', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)])),
                ('monthly_order6', models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)])),
            ],
        ),
        migrations.CreateModel(
            name='Vendor3',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('monthly_order7', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)])),
                ('monthly_order8', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)])),
                ('monthly_order9', models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)])),
            ],
        ),
        migrations.CreateModel(
            name='Vendor4',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('monthly_order10', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)])),
                ('monthly_order11', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)])),
                ('monthly_order12', models.PositiveIntegerField(default=0, help_text='Max Value is 25', validators=[django.core.validators.MaxValueValidator(25)])),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order10',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order11',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order12',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order4',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order5',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order6',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order7',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order8',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='monthly_order9',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='rupa',
        ),
    ]
