# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_auto_20170602_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mod_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor2',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor2',
            name='mod_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor3',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor3',
            name='mod_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor4',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor4',
            name='mod_count',
            field=models.IntegerField(default=0),
        ),
    ]
