# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='discount_index',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='employee_name',
            field=models.CharField(default='aaaa', max_length=120),
        ),
        migrations.AddField(
            model_name='demand',
            name='flavour_index',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='marketing_index',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='style_index',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
    ]
