# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0010_auto_20170501_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=50),
        ),
    ]
