# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0011_vendor_tax_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='demand',
        ),
        migrations.AddField(
            model_name='demand',
            name='demand_value',
            field=models.PositiveIntegerField(default=120000),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cost_index',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='delivery_index',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_index',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=50),
        ),
    ]
