# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0015_auto_20170502_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_flavour',
        ),
    ]
