# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0016_remove_demand_monthly_demand_flavour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCost',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_discount',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_marketing',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_1',
            field=models.CharField(default='Aaaa', max_length=120, unique=True, verbose_name='Name of the vendor 1'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_2',
            field=models.CharField(default='Aaaa', max_length=120, unique=True, verbose_name='Name of the vendor 2'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_3',
            field=models.CharField(default='Aaaa', max_length=120, unique=True, verbose_name='Name of the vendor 3'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_4',
            field=models.CharField(default='Aaaa', max_length=120, unique=True, verbose_name='Name of the vendor 4'),
        ),
    ]
