# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0017_auto_20170502_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name_1',
            field=models.CharField(default='Aaaa', max_length=120, verbose_name='Name of the vendor 1'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name_2',
            field=models.CharField(default='Aaaa', max_length=120, verbose_name='Name of the vendor 2'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name_3',
            field=models.CharField(default='Aaaa', max_length=120, verbose_name='Name of the vendor 3'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name_4',
            field=models.CharField(default='Aaaa', max_length=120, verbose_name='Name of the vendor 4'),
        ),
    ]
