# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0019_auto_20170502_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name_1',
            field=models.CharField(default='Aacva', max_length=120, verbose_name='Name of the vendor 1'),
        ),
    ]
