# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0020_auto_20170502_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='name_1',
        ),
    ]
