# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0021_remove_vendor_name_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name_4',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name_3',
        ),
    ]
