# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0022_auto_20170502_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='employee_name',
            new_name='employee_name_1',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='monthly_demand',
            new_name='monthly_demand_1',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='discount_index',
            new_name='monthly_demand_discount_1',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='flavour_index',
            new_name='monthly_demand_discount_2',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='marketing_index',
            new_name='monthly_demand_discount_3',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='style_index',
            new_name='monthly_demand_discount_4',
        ),
        migrations.AddField(
            model_name='demand',
            name='demand_1',
            field=models.PositiveIntegerField(default=12000),
        ),
        migrations.AddField(
            model_name='demand',
            name='demand_2',
            field=models.PositiveIntegerField(default=12000),
        ),
        migrations.AddField(
            model_name='demand',
            name='demand_3',
            field=models.PositiveIntegerField(default=12000),
        ),
        migrations.AddField(
            model_name='demand',
            name='demand_4',
            field=models.PositiveIntegerField(default=12000),
        ),
        migrations.AddField(
            model_name='demand',
            name='discount_index_1',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='discount_index_2',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='discount_index_3',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='discount_index_4',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='employee_name_2',
            field=models.CharField(default='aaab', max_length=120),
        ),
        migrations.AddField(
            model_name='demand',
            name='employee_name_3',
            field=models.CharField(default='aaac', max_length=120),
        ),
        migrations.AddField(
            model_name='demand',
            name='employee_name_4',
            field=models.CharField(default='aaad', max_length=120),
        ),
        migrations.AddField(
            model_name='demand',
            name='flavour_index_1',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='flavour_index_2',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='flavour_index_3',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='flavour_index_4',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='marketing_index_1',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='marketing_index_2',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='marketing_index_3',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='marketing_index_4',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_2',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_3',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_4',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_flavour_1',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_flavour_2',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_flavour_3',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_flavour_4',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_marketing_1',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_marketing_2',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_marketing_3',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_marketing_4',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_style_1',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_style_2',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_style_3',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_demand_style_4',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='style_index_1',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='style_index_2',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='style_index_3',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='demand',
            name='style_index_4',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
