# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0023_auto_20170502_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='demand_1',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='demand_2',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='demand_3',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='demand_4',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_discount_1',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_flavour_1',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_flavour_2',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_flavour_3',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_flavour_4',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_style_1',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_style_2',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_style_3',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_style_4',
        ),
    ]
