# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0027_auto_20170502_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='monthly_demand_discount_average',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='demand',
            name='monthly_demand_flavour_average',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='demand',
            name='monthly_demand_marketing_average',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
