# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0028_auto_20170502_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_discount_average',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_flavour_average',
        ),
    ]
