# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0029_auto_20170503_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_forcast', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_demand_marketing_average',
        ),
    ]
