# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0030_auto_20170503_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandforcast',
            name='demand_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
