# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0031_demandforcast_demand_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='vendor',
            name='demand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='new.Demand'),
            preserve_default=False,
        ),
    ]
