# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0034_vendor_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandforcast',
            name='unit_cost',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
