# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0035_demandforcast_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandforcast',
            name='unit_price',
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='demandforcast',
            name='unit_proft',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
