# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20170429_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_cost_unit', models.IntegerField(blank=True)),
                ('infra_cost', models.IntegerField(default=10000)),
                ('hr_cost', models.IntegerField(default=100)),
                ('marketing_cost', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_demand', models.PositiveIntegerField(default=10000)),
                ('demand_inc_value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('monthly_inc', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='vendor',
            name='delivery_time',
            field=models.IntegerField(default=30, help_text='in days'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='rm_cost',
            field=models.IntegerField(default=500, verbose_name='Per Unit Cost'),
        ),
    ]
